language: ruby
rvm:
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - ruby-head
  - jruby
  - rbx-2
  - rbx-3
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx-2
    - rvm: rbx-3
bundler_args: --without local_development
